repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/bin/black
        language: python
        types: [ python ]

      - id: isort
        name: isort
        entry: .venv/bin/isort
        language: python
        types: [ python ]

      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: python
        types: [ python ]

      - id: flake8
        name: flake8
        entry: .venv/bin/flake8
        language: python
        types: [ python ]
